name: Image test

on:
  push:
    branches:
      - main

jobs:
  docker-run:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run docker compose
        run: docker-compose up -d
      - name: Add permission
        run: chmod +x check-port.sh
      - name: Verify all port are active
        run: ./check-port.sh 4001 8081 9090 3000 8025 8161